import turtle
sam=turtle.Turtle()
sam.shape("turtle")
sam.color("blue")
sam.pensize(20)

sam.forward(100)
sam.backward(50)
sam.right(90)
sam.forward(100)
sam.left(90)
sam.penup()
sam.forward(75)
sam.pendown()
sam.left(90)
sam.forward(100)
sam.backward(50)
sam.right(90)
sam.forward(60)
sam.left(90)
sam.forward(50)
sam.backward(100)
